export interface BlogPost {
  slug: string;
  title: string;
  description: string;
  category: string;
  date: string; // ISO
  readTimeMinutes: number;
  content: string[];
}

export const BLOG_POSTS: BlogPost[] = [
  {
    slug: 'how-to-reconcile-meesho-settlement-report',
    title: 'How to Reconcile Your Meesho Settlement Report, Step by Step',
    description: 'A practical walkthrough for matching your Meesho settlement report against your own sales records, order by order.',
    category: 'Meesho',
    date: '2026-08-01',
    readTimeMinutes: 6,
    content: [
      'Every Meesho seller eventually hits the same wall: the amount in your bank account doesn\u2019t match what you expected from your sales. Reconciling your settlement report against your own sales register is the only way to find out why.',
      'Start by downloading two files from your Meesho Supplier Panel: the settlement report (Payments \u2192 Settlement) and your order/sales history for the same period. Both need to cover the same date range, or you\u2019ll end up comparing orders that were never meant to line up.',
      'Match by Sub Order No, not by product name or date \u2014 it\u2019s the only field guaranteed to be unique per transaction. For each order, compare your expected sale value against the Final Settlement Amount. A difference usually comes from one of four places: commission, forward or reverse shipping charges, a return that hasn\u2019t been credited, or TCS.',
      'Watch for orders that appear in your sales register but never show up in the settlement file at all \u2014 that\u2019s a missing settlement, and it\u2019s the discrepancy most sellers miss because there\u2019s no line to look at, just an absence.',
      'Doing this by hand in Excel works at low volume, but VLOOKUP-based matching breaks down fast once you\u2019re past a few hundred orders a month, especially with partial returns splitting one order across two settlement rows. That\u2019s the exact problem Settlr\u2019s reconciliation engine is built to handle \u2014 upload both files and it does the order-level matching automatically.',
    ],
  },
  {
    slug: 'amazon-settlement-report-explained',
    title: 'Amazon Settlement Report Explained: A Seller\u2019s Guide',
    description: 'What every column in your Amazon Seller Central settlement report actually means, and how to use it to verify your payout.',
    category: 'Amazon',
    date: '2026-08-03',
    readTimeMinutes: 7,
    content: [
      'Amazon\u2019s settlement report (Seller Central \u2192 Payments \u2192 All Statements \u2192 Download Flat File V2) is the only document that shows every financial event tied to your account for a settlement period \u2014 not a summary, but every individual line.',
      'The structure trips people up because it\u2019s long, not wide: instead of one row per order with separate columns for commission and shipping, you get multiple rows per order, each with an amount-type, an amount-description, and a single amount column. A "Principal" row is your item price. An "ItemFees" row with description "Commission" is Amazon\u2019s referral fee. Sum every row for an order-id and you get your net settlement for that order.',
      'The most common reconciliation mistake is comparing this report against your Business Reports data by order date. Don\u2019t \u2014 settlement reports are posted-date, meaning a transaction lands in whichever settlement period it was processed, not when the customer actually ordered. Refunds and reserve holds can widen that gap to weeks.',
      'Group by settlement-id first to confirm the sum of your amount column matches the total-amount for that period \u2014 if it doesn\u2019t, you\u2019re working with a truncated download, not a real discrepancy. Then group by order-id to check individual orders.',
      'For sellers running more than a couple hundred orders a month, manually pivoting a long-format CSV in Excel gets error-prone fast. Settlr reads Amazon\u2019s settlement format natively and aggregates it back to order-level automatically, so you\u2019re reviewing exceptions instead of building pivot tables every week.',
    ],
  },
  {
    slug: 'flipkart-settlement-reconciliation-mistakes',
    title: 'Flipkart Settlement Reconciliation: Common Mistakes Sellers Make',
    description: 'The recurring errors that cause Flipkart sellers to under- or over-estimate what they\u2019re actually owed.',
    category: 'Flipkart',
    date: '2026-08-05',
    readTimeMinutes: 6,
    content: [
      'Flipkart\u2019s settlement report is wide-format \u2014 one row per order with separate columns for commission, fixed fee, collection fee, shipping fee, and TCS \u2014 which makes it easier to read than Amazon\u2019s, but sellers still make the same handful of mistakes reconciling it.',
      'The first is assuming a full order pays out in one cycle. Flipkart frequently splits a single order\u2019s settlement across two dates \u2014 commission and fixed fee on one cycle, the shipping deduction on the next. If you reconcile cycle by cycle instead of order by order, you\u2019ll flag dozens of "missing" settlements that are actually just pending the second half.',
      'The second is not checking F-Assured fees against the right orders. F-Assured orders carry a premium fee in exchange for faster delivery commitments \u2014 if a non-F-Assured order gets charged the F-Assured rate, that\u2019s a real overcharge, but it only shows up if you\u2019re checking fee type against order flag, not just the total.',
      'The third is treating returns as a simple deduction. When a product comes back, Flipkart is supposed to reverse the commission it originally took \u2014 sellers who don\u2019t check for that reversal often assume they\u2019ve lost more margin on a return than they actually have.',
      'Because Flipkart deducts commission, fixed fee, collection fee, shipping, and TCS as separate line items, order-level reconciliation software can verify each deduction against your own rate expectations rather than just checking whether the final number "feels right." That per-fee visibility is where most recoverable revenue leakage hides.',
    ],
  },
  {
    slug: 'what-is-tcs-under-gst-for-ecommerce-sellers',
    title: 'What Is TCS Under GST for E-commerce Sellers?',
    description: 'A plain-language explanation of Tax Collected at Source under GST Section 52, and what it means for your marketplace settlements.',
    category: 'GST & Compliance',
    date: '2026-08-07',
    readTimeMinutes: 5,
    content: [
      'If you sell through Amazon, Flipkart, or Meesho, you\u2019ve probably noticed a "TCS" deduction on every settlement and wondered where that money actually goes.',
      'Under Section 52 of the CGST Act, e-commerce operators are required to collect 1% of the net taxable value of supplies made through their platform, and deposit it with the government on your behalf. This isn\u2019t an extra cost to you in the way commission is \u2014 it\u2019s tax you would have owed anyway, collected upfront rather than paid separately.',
      'The 1% typically splits as 0.5% CGST + 0.5% SGST for intra-state sales, or 1% IGST for inter-state sales. The marketplace reports this collection to the government, and it appears in your GSTR-2B as available credit \u2014 you claim it back when filing your GST returns.',
      'The practical risk isn\u2019t the deduction itself, it\u2019s reconciliation: the TCS deducted in your settlement report needs to match what actually shows up in your GSTR-2B. If a marketplace misreports or delays a TCS entry, you can end up unable to claim credit you\u2019re rightfully owed \u2014 and the only way to catch that early is comparing your settlement-level TCS figures against your GST filings, not just trusting the total.',
      'This is exactly the kind of mismatch that\u2019s invisible until you\u2019re looking at order-level data side by side \u2014 which is why TCS tracking is one of the fields Settlr pulls out explicitly in every reconciliation, rather than folding it into a generic "deductions" bucket.',
    ],
  },
  {
    slug: 'tds-vs-tcs-marketplace-sellers',
    title: 'TDS vs TCS for Marketplace Sellers: What\u2019s the Difference?',
    description: 'Two similar-sounding deductions on your settlement report, and why sellers need to track them separately.',
    category: 'GST & Compliance',
    date: '2026-08-09',
    readTimeMinutes: 5,
    content: [
      'TDS and TCS show up on the same settlement report, get confused constantly, and are actually governed by completely different laws.',
      'TCS (Tax Collected at Source) is a GST mechanism under Section 52 \u2014 the marketplace collects 1% of your taxable sales and deposits it against your GST liability. You claim it back as credit in your GST returns.',
      'TDS (Tax Deducted at Source) is an income-tax mechanism under Section 194-O \u2014 the marketplace deducts a percentage (commonly 0.1% to 1% depending on thresholds and your PAN/Aadhaar linkage status) from your gross sales as advance income tax. This gets credited against your income tax liability, not your GST liability, and shows up in Form 26AS rather than GSTR-2B.',
      'Flipkart, in particular, deducts both TDS and TCS on the same settlement, which means a single settlement report can carry two tax deductions that need to reconcile against two entirely different government systems \u2014 GSTR-2B for TCS, Form 26AS for TDS. Mixing them up in your books doesn\u2019t just cause a bookkeeping error; it can mean under-claiming credit you\u2019re owed on one side or the other.',
      'The safest habit is treating TDS and TCS as two separate line items from the moment you reconcile a settlement, never as one combined "tax deducted" figure \u2014 which is why reconciliation tools worth using break them out individually rather than netting them into your final settlement number.',
    ],
  },
  {
    slug: 'why-marketplace-payout-never-matches-sales-report',
    title: 'Why Your Marketplace Payout Never Matches Your Sales Report',
    description: 'The structural reasons a ₹1,00,000 sales month can settle at ₹78,000 in your bank account \u2014 and how to tell if that gap is normal.',
    category: 'Reconciliation Basics',
    date: '2026-08-11',
    readTimeMinutes: 6,
    content: [
      'This is the single most common question new marketplace sellers ask, usually after their first big sales month settles for noticeably less than expected: is a ₹1,00,000 sales month settling for ₹78,000 normal, or did something go wrong?',
      'Often, it\u2019s normal \u2014 to a point. Between commission (which varies by category, often 5\u201320%), shipping and logistics fees, TCS, and returns, a 15\u201325% gap between gross sales and net settlement isn\u2019t unusual on its own. The problem is that "normal-looking" and "actually correct" are two different things, and the only way to tell them apart is checking the deduction breakdown order by order.',
      'The real risk hides in what doesn\u2019t announce itself: an order that was delivered but never settled at all, a return where the commission was never reversed, a shipping fee calculated on the wrong weight slab, or TCS applied twice. None of these show up as an obviously wrong total \u2014 they just quietly shrink the number, and a seller checking only the bottom line has no way to notice.',
      'Industry estimates from firms working with Indian marketplace sellers put typical revenue leakage \u2014 money lost to exactly these kinds of errors \u2014 at 2\u20135% of gross sales. Against India\u2019s already-thin e-commerce margins of 10\u201320%, that can eat a fifth or more of actual profit.',
      'The fix isn\u2019t distrust of every settlement \u2014 it\u2019s order-level verification instead of total-level acceptance. Matching every order in your sales report against its corresponding settlement line, rather than eyeballing whether the final deposit "looks about right," is the only reliable way to separate expected deductions from ones worth disputing.',
    ],
  },
  {
    slug: 'amazon-2026-fee-changes-what-sellers-need-to-know',
    title: 'Amazon\u2019s 2026 Fee Changes: What Sellers Need to Know',
    description: 'A summary of recent referral fee and category changes on Amazon India, and how to verify they\u2019re being applied correctly on your settlements.',
    category: 'Amazon',
    date: '2026-08-13',
    readTimeMinutes: 5,
    content: [
      'Amazon periodically revises its referral fee structure across categories, and 2026 has been no exception \u2014 sellers have reported changes including a zero-referral-fee list for certain low-priced categories, alongside adjustments elsewhere.',
      'The practical challenge for sellers isn\u2019t knowing that fees changed \u2014 Amazon announces category-level changes in Seller Central \u2014 it\u2019s verifying that the change was actually applied correctly to every order after the effective date. Fee updates that roll out across a large catalog don\u2019t always apply cleanly to every SKU on day one.',
      'The only reliable way to check is comparing your settlement report\u2019s commission line against your own expected rate for each order\u2019s category, for orders both before and after the change took effect. A category that should now carry zero referral fee but is still showing a commission deduction is a legitimate, recoverable overcharge \u2014 not a rounding issue.',
      'This kind of category-level fee verification is tedious to do manually across hundreds of SKUs, but it\u2019s exactly where automated order-level reconciliation earns its keep: flagging every order where the actual commission charged doesn\u2019t match what the current fee schedule implies, so you\u2019re reviewing a short exception list instead of every line in the report.',
      'Whenever Amazon announces a fee change, treat the weeks immediately after the effective date as a priority reconciliation window \u2014 that\u2019s when misapplied fees are most likely to surface, and easiest to catch while the relevant orders are still recent enough to dispute.',
    ],
  },
  {
    slug: 'how-much-revenue-lost-to-marketplace-overcharges',
    title: 'How Much Revenue Are You Losing to Marketplace Overcharges?',
    description: 'A realistic look at revenue leakage rates for Indian marketplace sellers, and how to estimate your own exposure.',
    category: 'Reconciliation Basics',
    date: '2026-08-15',
    readTimeMinutes: 5,
    content: [
      'Every seller has heard some version of the claim that marketplaces overcharge sellers by 2\u20135% of revenue. It\u2019s a real, commonly cited range from firms specializing in marketplace reconciliation \u2014 but it\u2019s also a range, not a fact about your specific account, and the only way to know your actual number is to check.',
      'Overcharges cluster in a few predictable places: shipping fees calculated on the wrong weight or zone (common when a warehouse routes an order incorrectly), commission applied at the wrong category rate, F-Assured or premium fulfillment fees charged on orders that don\u2019t qualify for them, and returns where the original commission was never reversed.',
      'None of these show up as a single large, obviously-wrong number. They\u2019re small, per-order variances \u2014 often ₹20\u2013100 per affected order \u2014 that only become visible in aggregate once you\u2019re looking at hundreds or thousands of orders side by side.',
      'A useful gut-check: pull one month of settlement data, pick 20 random orders, and manually verify the commission and shipping charged against what you\u2019d expect for that category and weight. If more than one or two are off, it\u2019s worth reconciling the full month rather than assuming it\u2019s an isolated error.',
      'For sellers moving real volume, spot-checking 20 orders a month isn\u2019t enough coverage to catch a systemic issue \u2014 a wrong weight-slab assignment affects every order from that warehouse until it\u2019s fixed. Full order-level reconciliation across every settlement, not just a sample, is what actually surfaces that pattern early enough to matter.',
    ],
  },
  {
    slug: 'rto-and-returns-effect-on-settlement',
    title: 'RTO and Returns: How They Affect Your Marketplace Settlement',
    description: 'Understanding how returned-to-origin orders and customer returns flow through your settlement report.',
    category: 'Reconciliation Basics',
    date: '2026-08-17',
    readTimeMinutes: 6,
    content: [
      'Returns are where most sellers lose track of their own numbers, because a single returned order can touch a settlement report two or three separate times across different periods.',
      'When an order is dispatched, it typically settles once as a normal sale. If the customer later returns it (or it comes back as RTO \u2014 return to origin, meaning it never reached the customer), a second settlement entry appears reversing some or all of the original amount \u2014 sometimes in the very next cycle, sometimes weeks later depending on how long the return takes to process.',
      'The commission question is the one sellers get wrong most often: marketplaces are generally supposed to reverse the commission they took on the original sale when an order is returned. If that reversal doesn\u2019t appear, you\u2019ve effectively paid commission on a sale that didn\u2019t happen \u2014 a genuine, disputable discrepancy, not a normal cost of doing business.',
      'Reverse shipping charges add another layer: some marketplaces charge the seller a reverse pickup fee on top of losing the sale, which is a legitimate cost, but it needs to be checked against your actual return volume rather than assumed.',
      'Because returns don\u2019t resolve in the same settlement cycle as the original sale, reconciling them requires linking a return entry back to its original forward-sale order ID across periods \u2014 something spreadsheets handle poorly once you\u2019re past a handful of returns a month, and where dedicated reconciliation software earns its value by tracking the link automatically.',
    ],
  },
  {
    slug: 'gst-reconciliation-guide-for-ecommerce-sellers',
    title: 'GST Reconciliation for E-commerce Sellers: A Complete Guide',
    description: 'How to reconcile your marketplace settlements against your GST filings, and why the two rarely match on the first pass.',
    category: 'GST & Compliance',
    date: '2026-08-19',
    readTimeMinutes: 7,
    content: [
      'Marketplace settlement reconciliation and GST reconciliation are related but distinct exercises, and conflating them is where a lot of sellers get into trouble at filing time.',
      'Settlement reconciliation asks: did the marketplace pay me the right amount for what I sold? GST reconciliation asks a different question: does the tax I\u2019ve reported on my sales match what the marketplace reported collecting TCS on, and does the ITC I\u2019m claiming match what shows up in my GSTR-2B?',
      'The two documents often disagree because they\u2019re built on different timing. Your books might recognize a sale on the order date; the marketplace\u2019s TCS reporting follows the settlement date. Over a large enough volume, that timing gap alone can create a mismatch between your GSTR-1 output and what the marketplace\u2019s TCS filings imply, even when nothing is actually wrong.',
      'The practical sequence that avoids most GST-time surprises: reconcile settlements against your sales records first (catching missing payments and wrong deductions), then separately reconcile the TCS and commission-GST figures from those same settlements against your GSTR-2B. Trying to do both in one pass tends to produce false positives \u2014 discrepancies that look like GST problems but are actually just settlement timing.',
      'A settlement report with commission, TCS, and net amount already broken out into separate fields \u2014 rather than netted into one final number \u2014 makes this second-pass GST reconciliation dramatically faster, because you\u2019re not first re-deriving the tax components from a lump-sum figure before you can even start comparing them.',
    ],
  },
  {
    slug: 'meesho-vs-amazon-vs-flipkart-seller-fees',
    title: 'Meesho vs Amazon vs Flipkart: Comparing Seller Fees',
    description: 'How commission, shipping, and fee structures differ across India\u2019s three biggest marketplaces.',
    category: 'Marketplace Comparison',
    date: '2026-08-02',
    readTimeMinutes: 6,
    content: [
      'Sellers running the same catalog across Meesho, Amazon, and Flipkart often assume the fee structures are roughly comparable. They\u2019re not, and the differences matter for pricing decisions, not just bookkeeping.',
      'Meesho is generally the lowest-fee platform for smaller sellers, with a fee structure historically built around zero or low commission for many categories, making its margin math simpler \u2014 though shipping and return charges still apply and need checking.',
      'Amazon\u2019s referral fees vary widely by category (roughly 5\u201320%+ depending on product type), and layer on additional charges depending on fulfillment method \u2014 FBA storage and fulfillment fees if Amazon handles logistics, versus Easy Ship costs if you self-ship. A product that\u2019s profitable in one fulfillment model can be marginal in another.',
      'Flipkart\u2019s fee structure packs commission, a fixed fee, a collection fee, and (for premium delivery commitments) an F-Assured fee into the same settlement \u2014 several distinct charges rather than one blended commission rate, which is part of why Flipkart settlement reports have more columns than Meesho\u2019s.',
      'Because the fee structures don\u2019t map cleanly onto each other, a per-order margin calculation that works for one marketplace usually needs separate assumptions for the others \u2014 which is exactly why reconciling each platform against its own settlement report, rather than a single blended spreadsheet formula, produces more trustworthy numbers.',
    ],
  },
  {
    slug: 'how-to-read-flipkart-settlement-report',
    title: 'How to Read a Flipkart Settlement Report',
    description: 'A column-by-column breakdown of what\u2019s in your Flipkart Seller Hub settlement export.',
    category: 'Flipkart',
    date: '2026-08-04',
    readTimeMinutes: 5,
    content: [
      'Flipkart\u2019s settlement report, downloaded from Seller Hub under Payments, is order-item-level: one row per order or order item, with each deduction broken into its own column rather than netted into a single figure.',
      'Order ID and Order Item ID identify the transaction \u2014 use Order ID as your primary match key against your own sales records. Total Offer Price (or Selling Price) is the gross amount the customer paid before deductions.',
      'From there, Commission (category-based percentage), Fixed Fee (a flat per-order charge), Collection Fee (for COD or online payment processing), and Shipping Fee are deducted in sequence. If the order qualified for F-Assured, an additional premium fee applies. TCS and TDS are deducted last, as required withholdings rather than marketplace charges.',
      'The Final Settlement Amount column is what actually lands in your bank \u2014 the sum of the price minus every deduction above. If that number doesn\u2019t match your expected net for the order, work backward through the individual fee columns rather than the total; it\u2019s much faster to spot "commission looks 3% too high" than to try to guess which of five deductions is wrong from the final figure alone.',
      'Because every deduction has its own column, Flipkart\u2019s report is actually easier to automate reconciliation against than a long-format report like Amazon\u2019s \u2014 each fee type maps directly to a field, which is the structure Settlr\u2019s Flipkart parser is built around.',
    ],
  },
  {
    slug: 'signs-you-need-reconciliation-software',
    title: '5 Signs You Need Reconciliation Software as a Marketplace Seller',
    description: 'When manual Excel reconciliation stops being sustainable, and what to look for in a tool instead.',
    category: 'Reconciliation Basics',
    date: '2026-08-06',
    readTimeMinutes: 5,
    content: [
      'Most sellers start out reconciling settlements manually in Excel, and for a while, that\u2019s the right call \u2014 it\u2019s free and it works at low volume. Here\u2019s how to tell when it stops working.',
      'One: reconciliation is eating more than a couple of hours a week. Manual VLOOKUP-based matching scales roughly linearly with order count, but the time spent chasing exceptions scales faster than that, because more volume means more edge cases (split settlements, partial returns, duplicate order IDs).',
      'Two: you\u2019re selling on more than one marketplace. Each platform\u2019s settlement format is different enough that maintaining separate reconciliation logic for Amazon, Flipkart, and Meesho in one spreadsheet gets unwieldy fast, and it\u2019s easy for formulas built for one platform\u2019s columns to silently misread another\u2019s.',
      'Three: you\u2019ve found a discrepancy by accident rather than by systematic check. If the only mismatches you catch are the ones large enough to notice while skimming a total, smaller recurring overcharges are almost certainly slipping through unnoticed.',
      'Four: returns and partial settlements are common enough that manual matching regularly breaks. Five: you need the reconciled output for GST filing or a CA review, and hand-built spreadsheets aren\u2019t producing a consistent, audit-ready trail. If two or more of these sound familiar, it\u2019s usually cheaper to switch to dedicated reconciliation software than to keep absorbing the manual hours.',
    ],
  },
  {
    slug: 'manual-excel-vs-automated-reconciliation',
    title: 'Manual Excel Reconciliation vs Automated Tools: Pros and Cons',
    description: 'An honest comparison of spreadsheet-based reconciliation against dedicated software, for sellers deciding which to use.',
    category: 'Reconciliation Basics',
    date: '2026-08-08',
    readTimeMinutes: 6,
    content: [
      'Excel isn\u2019t a bad reconciliation tool \u2014 it\u2019s a genuinely fine one at low volume, and switching to software before you need to is just an added cost. The honest comparison depends entirely on where you are.',
      'Excel\u2019s advantages: no subscription cost, full control over the logic, and no dependency on a third-party tool correctly parsing your specific settlement format. For a seller doing under a few hundred orders a month on a single marketplace, a well-built VLOOKUP or INDEX-MATCH sheet reconciles perfectly well.',
      'Where Excel breaks down is one-to-many matching \u2014 a single order with multiple linked settlement rows (a sale, a later return, a separate TDS line) doesn\u2019t fit a simple lookup formula without significant manual rework each time the pattern occurs. Multiply that across a few thousand orders and the spreadsheet either gets fragile or the seller starts skipping edge cases to save time.',
      'Automated tools trade that manual overhead for a monthly cost, in exchange for handling multi-row aggregation, column-format differences between marketplaces, and audit-trail generation automatically. The tradeoff only makes sense once the time saved is worth more than the subscription \u2014 which, for most sellers, tends to happen somewhere between a few hundred and a couple thousand orders a month, depending on how many marketplaces they\u2019re juggling.',
      'A reasonable middle path: keep using Excel until reconciliation starts taking more than an hour or two a week, then switch \u2014 and when you do, look for a tool that shows its work at the order level rather than just producing a summary number, so you can still verify it the way you\u2019d verify your own spreadsheet.',
    ],
  },
  {
    slug: 'understanding-marketplace-commission-structures-india',
    title: 'Understanding Marketplace Commission Structures in India',
    description: 'How commission rates are actually set across categories, and why they change more often than sellers expect.',
    category: 'Marketplace Comparison',
    date: '2026-08-10',
    readTimeMinutes: 5,
    content: [
      'Commission isn\u2019t a single number for any marketplace \u2014 it\u2019s a category-by-category rate card that marketplaces revise periodically, sometimes with little advance notice to individual sellers.',
      'Amazon and Flipkart both structure commission as a percentage of the selling price, varying by product category \u2014 electronics typically sit at the lower end (single digits), while categories like apparel and home goods can run considerably higher. The exact rate for your specific sub-category is usually buried in a rate card PDF or seller dashboard page that most sellers check once at listing time and never again.',
      'That "check once" habit is the risk. Rate cards change, sometimes for an entire category, sometimes for narrower sub-segments within it. If your product moved sub-categories, or the marketplace revised the rate, you won\u2019t know unless you\u2019re comparing your actual settled commission against the current rate card periodically \u2014 not just trusting last year\u2019s number.',
      'Meesho\u2019s structure has historically been simpler and lower for many categories, which is part of why it\u2019s often the entry point for new sellers, but "simpler" doesn\u2019t mean "static" \u2014 it\u2019s still worth verifying periodically rather than assuming.',
      'The practical habit worth building: whenever a marketplace announces a fee update, spend ten minutes checking your last month\u2019s settled commission against the new rate for your top few SKUs by volume. Catching a misapplied rate change in month one is a lot easier than untangling it after six months of settlements.',
    ],
  },
  {
    slug: 'how-to-dispute-wrong-deduction-amazon',
    title: 'How to Dispute a Wrong Deduction on Amazon',
    description: 'The practical steps for filing and winning a reimbursement claim once you\u2019ve identified an overcharge.',
    category: 'Amazon',
    date: '2026-08-12',
    readTimeMinutes: 6,
    content: [
      'Finding an overcharge is only half the job \u2014 getting Amazon to reverse it requires evidence in a specific format, submitted through the right channel, before the claim window closes.',
      'Start by isolating the exact order-id and settlement-id where the discrepancy occurs, along with the amount-type and amount-description rows involved. A vague claim ("my shipping fees seem high this month") gets deprioritized; a specific one ("Order 123-4567890, settlement ID XYZ, charged ₹142 shipping against a ₹250g item, expected ₹85 based on the published Easy Ship rate card") gets reviewed.',
      'Claims are filed through Seller Central\u2019s Case Log, under the relevant category \u2014 Payments for settlement discrepancies, Fulfillment for FBA-specific reimbursement claims like lost or damaged inventory. Attach the settlement report excerpt and your own calculation showing the expected charge, not just the disputed one.',
      'Claim windows are tighter than most sellers assume \u2014 many reimbursement categories have to be filed within 60\u201390 days of the transaction, after which Amazon can decline purely on timing regardless of whether the underlying claim is valid. This is the strongest argument for reconciling monthly rather than quarterly: a discrepancy caught in month one still has a live claim window, one caught in month four often doesn\u2019t.',
      'Keep a simple log of every claim filed, the amount, and the outcome \u2014 not just for your own records, but because a pattern of the same error recurring (say, consistently wrong weight-slab shipping charges from one warehouse) is itself useful evidence when escalating a claim that Amazon initially declines.',
    ],
  },
  {
    slug: 'cod-reconciliation-for-indian-sellers',
    title: 'Cash on Delivery (COD) Reconciliation for Indian Sellers',
    description: 'Why COD orders need a different reconciliation approach than prepaid orders, and how to track the collection-to-bank-credit gap.',
    category: 'Reconciliation Basics',
    date: '2026-08-14',
    readTimeMinutes: 6,
    content: [
      'COD still accounts for a meaningful share of orders on Indian marketplaces, and it introduces a reconciliation step that prepaid orders skip entirely: the gap between when the customer pays cash and when that cash actually reaches your bank as a settlement.',
      'A prepaid order settles against a payment the marketplace already collected digitally at checkout. A COD order settles against cash the delivery partner collected in person \u2014 which means there\u2019s an extra handoff (courier to marketplace) where money can go missing, get remitted late, or get remitted short.',
      'The practical tracking sequence for a COD order runs: dispatch, then delivery confirmation, then a remittance-expectation window (typically 5\u20137 days after delivery, though this varies by marketplace and seller tier), then the actual bank credit. An order that\u2019s delivered but hasn\u2019t settled within that window isn\u2019t necessarily wrong \u2014 but it needs to move from "normal" to "flagged for follow-up" once it\u2019s meaningfully overdue.',
      'COD collection charges are also worth checking separately from standard shipping fees \u2014 some marketplaces apply an additional COD handling fee on top of logistics costs, which is legitimate, but easy to mistake for a duplicate shipping charge if you\u2019re not looking at the fee-type breakdown.',
      'Because COD orders carry this extra timing dimension, reconciling them against a simple "delivered = paid" assumption produces false positives constantly. Tracking each COD order through its full cycle \u2014 not just comparing a snapshot total \u2014 is the only way to tell a genuinely missing remittance from one that\u2019s simply still in transit.',
    ],
  },
  {
    slug: 'gstr1-gstr3b-ecommerce-sellers',
    title: 'GSTR-1 and GSTR-3B: What E-commerce Sellers Must Know',
    description: 'How marketplace sales flow into your monthly GST returns, and where settlement data and filing data commonly diverge.',
    category: 'GST & Compliance',
    date: '2026-08-16',
    readTimeMinutes: 6,
    content: [
      'GSTR-1 (outward supplies) and GSTR-3B (summary return with tax payment) are the two filings every GST-registered marketplace seller deals with monthly, and both depend on sales data that ultimately needs to tie back to your settlement reports.',
      'GSTR-1 reports your outward supplies \u2014 essentially, what you sold and the tax on it. For marketplace sellers, this should reflect actual sales, not settled amounts; a sale is a sale for GST purposes regardless of whether the marketplace has paid you yet. This is a common point of confusion: don\u2019t report only what\u2019s settled and skip pending orders.',
      'GSTR-3B is the summary return where you declare total tax liability and claim input tax credit, including the TCS your marketplace has collected on your behalf (visible in your GSTR-2B). If the TCS you\u2019re claiming doesn\u2019t match what the marketplace actually reported, the mismatch surfaces here \u2014 which is why TCS reconciliation against settlement data matters even for sellers who otherwise never touch their raw settlement reports.',
      'Returns and cancellations need to flow through as credit notes in your GSTR-1, adjusting your originally reported liability \u2014 skipping this step means you\u2019re paying GST on sales that were later reversed.',
      'The sequencing that avoids most filing-time scrambles: reconcile settlements against sales monthly (catching missing payments and wrong deductions early), and separately verify TCS figures against GSTR-2B before filing GSTR-3B \u2014 rather than discovering a TCS mismatch during the filing itself, when there\u2019s much less room to investigate before the deadline.',
    ],
  },
  {
    slug: 'calculate-true-profit-margin-after-marketplace-fees',
    title: 'How to Calculate Your True Profit Margin After Marketplace Fees',
    description: 'Why listing price minus cost price overstates margin, and what a realistic per-order profit calculation actually includes.',
    category: 'Reconciliation Basics',
    date: '2026-08-18',
    readTimeMinutes: 6,
    content: [
      'A lot of sellers price products based on selling price minus product cost, see a healthy-looking margin, and then wonder months later why the business doesn\u2019t feel as profitable as the spreadsheet suggested. The gap is almost always marketplace fees that never made it into the original calculation.',
      'A realistic per-order margin needs to subtract, in addition to product cost: commission (category-specific, not a flat assumption), shipping or logistics fees (which vary by weight and zone, not a flat per-order estimate), TCS (1%, recoverable as GST credit but still a cash-flow timing cost), and an amortized allowance for returns \u2014 not zero, since some percentage of orders will come back regardless of category.',
      'The return allowance is the piece most sellers skip entirely. If your category runs a 10% return rate and a return costs you the original commission plus a reverse shipping fee, that cost needs to be spread across all orders in your margin math, not treated as a one-off loss when it happens.',
      'The only way to get these numbers right instead of estimating them is working backward from actual settlement data \u2014 pulling your real average commission rate, real average shipping cost, and real return rate for a category over the last few months, rather than using the headline rate-card numbers, which don\u2019t account for how weight-slab or category-tier variance actually plays out on your specific catalog.',
      'Once you have real, settlement-derived averages per category, pricing decisions get a lot more reliable \u2014 and it becomes obvious which SKUs are quietly running at breakeven or a loss once every fee is actually accounted for, not just the ones you can see on the surface.',
    ],
  },
  {
    slug: 'f-assured-flipkart-premium-fees-explained',
    title: 'F-Assured and Other Flipkart Premium Fees Explained',
    description: 'What F-Assured status means for your fees, and how to verify it\u2019s only being charged where it should be.',
    category: 'Flipkart',
    date: '2026-08-20',
    readTimeMinutes: 5,
    content: [
      'F-Assured is Flipkart\u2019s badge for products that meet certain quality and delivery-speed commitments \u2014 it can boost visibility and buyer trust, but it also comes with a premium fee that stacks on top of standard commission, fixed fee, and shipping.',
      'The reconciliation issue isn\u2019t the fee itself \u2014 it\u2019s existing, when it should exist, and not existing when it shouldn\u2019t. Two failure modes show up in practice: an F-Assured fee charged on an order for a product that isn\u2019t actually F-Assured-flagged (a straightforward overcharge), and an F-Assured order where the premium fee is missing but you were still held to the faster delivery commitment without the corresponding compensation structure.',
      'Verifying this requires cross-referencing your product catalog\u2019s F-Assured status against each order\u2019s settlement line \u2014 something that\u2019s only practical if you\u2019re tracking status at the SKU level, not assuming it applies uniformly across your whole catalog.',
      'Similar scrutiny applies to other Flipkart premium program fees \u2014 Flipkart Plus-related charges, Smart-Picked Fee (SPF) on select fulfillment paths \u2014 each of which is legitimate when correctly applied and a real overcharge when applied to an order that doesn\u2019t qualify.',
      'Because these premium fees are conditional on order-specific flags rather than flat category rates, they\u2019re the category of overcharge most likely to be a genuine tooling or data error on the marketplace side, rather than a policy you simply weren\u2019t aware of \u2014 which makes them worth disputing when you find them, not just noting for future pricing.',
    ],
  },
  {
    slug: 'common-reasons-missing-settlements',
    title: 'Common Reasons for Missing Settlements on Marketplaces',
    description: 'Why an order can be delivered, confirmed, and still never appear in your settlement report \u2014 and how to track it down.',
    category: 'Reconciliation Basics',
    date: '2026-08-21',
    readTimeMinutes: 5,
    content: [
      'A missing settlement is the discrepancy sellers find latest, because there\u2019s nothing wrong to spot on a settlement report \u2014 the order just isn\u2019t there. You only catch it by comparing your own sales records against the settlement file and noticing an order that exists on one side but not the other.',
      'The most common cause is simple timing: the order was delivered near the end of a settlement cycle and will settle in the next one. This isn\u2019t actually missing, just pending \u2014 which is why any missing-settlement check needs a reasonable buffer window (typically 7\u201314 days past delivery, depending on the marketplace) before flagging something as a real problem rather than a timing artifact.',
      'Past that buffer, genuine causes include: an order stuck in a dispute or claim status that\u2019s holding up settlement, a return or cancellation that removed the order from the payout queue without a clear corresponding note in your sales register, or, less commonly, a processing error on the marketplace\u2019s side that dropped the transaction from a settlement batch entirely.',
      'Account-level holds are another real cause worth checking \u2014 if your account had a policy violation, a bank verification issue, or a reserve applied, entire batches of otherwise-normal orders can be delayed until the hold clears, which looks identical to individual missing settlements unless you check your account status directly.',
      'Tracking missing settlements systematically \u2014 not just noticing the occasional obvious one \u2014 requires comparing full order lists against full settlement lists every cycle, which is tedious manually but is exactly the kind of set-difference check reconciliation software handles as a byproduct of normal order-id matching.',
    ],
  },
  {
    slug: 'prepare-for-gst-audit-as-online-seller',
    title: 'How to Prepare for a GST Audit as an Online Seller',
    description: 'What auditors actually check for e-commerce sellers, and how clean settlement reconciliation makes the process faster.',
    category: 'GST & Compliance',
    date: '2026-08-22',
    readTimeMinutes: 6,
    content: [
      'A GST audit for an e-commerce seller looks different from one for a traditional retailer, mostly because of TCS and the sheer number of individual transactions involved \u2014 auditors typically want to see that your reported sales, your TCS claims, and your marketplace settlement data all tell a consistent story.',
      'The core documents an auditor will want: your GSTR-1 and GSTR-3B filings for the audit period, your GSTR-2B showing TCS credit claimed, your marketplace settlement reports for the same period, and ideally a reconciliation showing how the numbers in each connect to each other \u2014 not just that they exist separately.',
      'The most common finding in these audits isn\u2019t fraud, it\u2019s timing mismatches that were never explained: sales recognized in one period showing settlement or TCS activity in a different one, with no note explaining why. Auditors generally accept legitimate timing gaps (settlement dates lag order dates) \u2014 what they flag is an unexplained, undocumented gap that looks like it could be either an error or something worse.',
      'The single most useful thing a seller can do ahead of an audit is have order-level reconciliation records on hand, not just monthly summary totals \u2014 being able to show, for any specific order an auditor asks about, its sales record, its settlement record, its TCS treatment, and the reason for any variance, turns what could be a multi-day back-and-forth into a same-day answer.',
      'This is also the strongest argument for reconciling monthly rather than only at filing time or audit time: reconstructing order-level detail six or twelve months after the fact, from memory or scattered files, is dramatically harder than having it already organized as you go.',
    ],
  },
  {
    slug: 'multi-marketplace-selling-managing-reconciliation',
    title: 'Multi-Marketplace Selling: Managing Reconciliation Across Platforms',
    description: 'How to keep reconciliation consistent and manageable once you\u2019re selling on Amazon, Flipkart, and Meesho simultaneously.',
    category: 'Marketplace Comparison',
    date: '2026-08-22',
    readTimeMinutes: 6,
    content: [
      'Selling on multiple marketplaces multiplies revenue potential, but it also multiplies reconciliation complexity in a way that isn\u2019t linear \u2014 three marketplaces don\u2019t mean three times the work, they mean three different report formats, three different settlement cadences, and three sets of fee logic to keep straight simultaneously.',
      'The format problem is the most immediate: Amazon\u2019s settlement export is long-format with a single amount column split across multiple rows per order; Flipkart\u2019s is wide-format with each fee type in its own column; Meesho\u2019s sits somewhere in between. A spreadsheet formula built for one won\u2019t work unmodified on another, and maintaining three separate reconciliation sheets in parallel is where a lot of manual processes quietly fall apart.',
      'The timing problem compounds it: each marketplace settles on its own schedule (Amazon\u2019s cycles differ from Flipkart\u2019s T+7-to-T+10 windows, which differ again from Meesho\u2019s), so "this month\u2019s reconciliation" means three overlapping-but-different date ranges, not one clean calendar month across all three.',
      'The practical approach that scales is normalizing every marketplace\u2019s data into the same internal structure \u2014 order ID, gross amount, commission, shipping, TCS, net amount \u2014 regardless of what each platform originally called those columns, so that once normalized, the actual matching and discrepancy logic is identical across all three. Building and maintaining that normalization layer by hand in Excel is possible but brittle; it\u2019s the exact problem purpose-built multi-marketplace reconciliation tools are designed to solve, since the underlying reconciliation logic genuinely is marketplace-agnostic once the data\u2019s in a consistent shape.',
      'Whatever approach you use, keep each marketplace\u2019s reconciliation as a distinct pass rather than blending all three into one combined spreadsheet \u2014 it\u2019s much easier to spot "something\u2019s wrong with Flipkart this month" when Flipkart\u2019s numbers aren\u2019t averaged in with Amazon\u2019s and Meesho\u2019s.',
    ],
  },
  {
    slug: 'real-cost-of-manual-bookkeeping-ecommerce',
    title: 'The Real Cost of Manual Bookkeeping for E-commerce Sellers',
    description: 'Accounting for the hidden costs of spreadsheet-based reconciliation \u2014 time, missed discrepancies, and audit risk.',
    category: 'Reconciliation Basics',
    date: '2026-08-22',
    readTimeMinutes: 6,
    content: [
      'The visible cost of manual bookkeeping is zero \u2014 no subscription fee, just time. The real cost is almost always higher than sellers estimate, because most of it is invisible until something goes wrong.',
      'Start with time, since it\u2019s the easiest to quantify: sellers doing manual settlement reconciliation across a few hundred orders a month typically report somewhere between two and six hours a week, depending on how many marketplaces they\u2019re on and how many exceptions (returns, splits, missing settlements) show up. At even a modest hourly value for a founder\u2019s time, that adds up to a real monthly cost \u2014 it just doesn\u2019t appear on any invoice.',
      'Then there\u2019s the cost of what manual reconciliation misses. Independent studies on manual VLOOKUP-style reconciliation put its match accuracy around 50\u201355%, versus roughly 85\u201390% for structured tooling \u2014 meaning close to half of transactions in a manual process may not get fully verified, which is exactly where small recurring overcharges go uncaught month after month.',
      'The audit-readiness cost is the least visible until it\u2019s suddenly very visible: reconstructing six months of order-level detail from scattered spreadsheets during a GST audit or a dispute with a marketplace takes far longer than maintaining an organized reconciliation trail as you go, and the pressure of doing it under a deadline increases the odds of further errors.',
      'None of this means manual bookkeeping is wrong at low volume \u2014 it\u2019s a genuinely reasonable choice early on. The point is that "free" and "costless" aren\u2019t the same thing, and the actual cost curve (time plus missed discrepancies plus audit risk) tends to cross over the cost of dedicated software earlier than most sellers assume.',
    ],
  },
  {
    slug: 'best-practices-weekly-marketplace-payment-reconciliation',
    title: 'Best Practices for Weekly Marketplace Payment Reconciliation',
    description: 'A practical cadence and checklist for staying on top of settlements without it becoming a full-time job.',
    category: 'Reconciliation Basics',
    date: '2026-08-22',
    readTimeMinutes: 5,
    content: [
      'Monthly reconciliation is common, but weekly reconciliation catches problems while claim windows are still wide open and while the relevant orders are still fresh enough to investigate easily \u2014 the tradeoff is needing a routine that doesn\u2019t eat a disproportionate amount of time each week.',
      'A workable weekly routine: download the latest settlement export and your sales records for the same window, run the match, and spend your time only on the exceptions \u2014 orders that didn\u2019t match cleanly \u2014 rather than re-verifying every order that settled exactly as expected. If your process has you reviewing matched orders as carefully as mismatched ones, it\u2019s taking longer than it needs to.',
      'Triage exceptions by dollar impact and claim-window urgency, not just by count. A handful of large discrepancies with a closing claim window matter more this week than a longer list of small, well-within-window ones \u2014 address the time-sensitive items first, batch the rest for a monthly deeper pass.',
      'Keep a running log of disputes filed and their outcomes. Beyond tracking individual claims, this log is what eventually reveals patterns \u2014 a specific warehouse consistently mis-weighing shipments, a specific category consistently mis-rated on commission \u2014 that are worth escalating as a systemic issue rather than fighting order by order forever.',
      'Whatever cadence you settle on, consistency matters more than frequency \u2014 a reconciliation habit that happens reliably every week, even briefly, catches more real problems over a year than an ambitious daily process that gets abandoned after a month. Start with a cadence you can actually sustain, then tighten it once it\u2019s a habit rather than a chore.',
    ],
  },
];

export function getBlogPost(slug: string): BlogPost | undefined {
  return BLOG_POSTS.find((p) => p.slug === slug);
}
